services:
  - type: web
    name: internal-system
    env: node
    rootDir: backend
    buildCommand: npm install && npm rebuild sqlite3
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000

